## Docker compose that launches an ollama server, a redis instance, an FastAPI built from the ollprox directory

services:

  ollama:
    image: ollama/ollama:latest
    container_name: ollama_server  
    volumes:
      - "{OLLAMA_LOCAL_DATA:-ollama}:/root/.ollama/"
    restart: unless-stopped
    runtime: nvidia


  redis:
    image: redis:latest
    container_name: redis_cache
    volumes:
      - redis_data:/data
    restart: unless-stopped


  ollprox:
    build: ./ollprox
    container_name: ollama_proxy
    ports:
      - "8000:${EXTERNAL_PORT:-8000}"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    env_file:
      - ./.env
    depends_on:      
      - ollama
      - redis
    restart: unless-stopped

    volumes:
      - ${API_KEY_FILE:-./api_keys.txt}:/api_keys.txt  # Mount the API key file if specified

volumes:
  ollama_data:
  redis_data:


